[package]
name = "d-ig"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/Owen-Dechow/d-ig"
description = ".gitignore cli manager"

[features]
test = []

[dependencies]
